<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="Key">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z@][a-zA-Z0-9\-_]*" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="Def">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Key" type="Key" />
				<xs:element name="Class" type="xs:string" />
				<xs:element name="Label" type="xs:string" minOccurs="0" />
				<xs:element name="Disabled" type="xs:boolean" minOccurs="0" />
				<xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
			</xs:sequence>
			<xs:attribute ref="Root" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:attribute name="Root" type="Key" />


	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Def" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
