<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<PackageId>cyv.Lithium.Core</PackageId>
		<Authors>Chris Grassi</Authors>
		<Description>Core utilities for the cyv.Lithium packages.</Description>

		<RepositoryUrl>https://github.com/cyv-cg/lithium</RepositoryUrl>
		<PackageProjectUrl>https://github.com/cyv-cg/lithium</PackageProjectUrl>
		<RespositoryType>git</RespositoryType>
		<Copyright>Copyright (c) Chris Grassi 2026</Copyright>
		<RepositoryBranch>main</RepositoryBranch>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<Nullable>enable</Nullable>
		<RootNamespace>Lithium</RootNamespace>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
</Project>
