<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="cyv.Lithium.Core" Version="$(CoreVersion)" />
		<PackageReference Include="cyv.Lithium.Defs" Version="$(DefsVersion)" />
		<PackageReference Include="cyv.Lithium.Strings" Version="$(StringsVersion)" />

		<PackageReference Include="Fluent.Net" Version="1.0.63" />
	</ItemGroup>

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0</TargetFramework>

		<PackageId>cyv.Lithium</PackageId>
		<Authors>Chris Grassi</Authors>
		<Description>Library for dynamically loading resources from XML at runtime.</Description>

		<IsPackable>true</IsPackable>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<NoPackageAnalysis>true</NoPackageAnalysis>
	</PropertyGroup>
</Project>
