<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\Lithium.Strings\Lithium.Strings.csproj" />
		<ProjectReference Include="..\Lithium.Core\Lithium.Core.csproj" />
	</ItemGroup>
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>Lithium</RootNamespace>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageId>cyv.Lithium</PackageId>
		<Version>0.1.0</Version>
		<Authors>Chris Grassi</Authors>
		<Description>Library for dynamically loading resources from XML at runtime.</Description>
	</PropertyGroup>
</Project>
