<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="cyv.Lithium.Core" Version="0.1.6-gc4c787bde5" />
		<PackageReference Include="cyv.Lithium.Defs" Version="0.1.6-gc4c787bde5" />
		<PackageReference Include="cyv.Lithium.Strings" Version="0.1.6-gc4c787bde5" />

		<PackageReference Include="Fluent.Net" Version="1.0.63" />
	</ItemGroup>

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0</TargetFramework>

		<PackageId>cyv.Lithium</PackageId>
		<Authors>Chris Grassi</Authors>
		<Description>Library for dynamically loading resources from XML at runtime.</Description>

		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>
</Project>
