<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Lithium.Defs\Lithium.Defs.csproj" />
		<Reference Include="TestAssembly01">
			<HintPath>__test_assemblies__\TestAssembly01\Lithium.Defs.Tests.TestAssembly01.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Include="__mocks__\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<EmbeddedResource Include="__resources__/**/*.xml" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="__test_assemblies__/**/*.cs" />
	</ItemGroup>
</Project>
