name: Build and Test Lithium.sln

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore "Lithium.sln"

      - name: Build
        run: dotnet build "Lithium.sln" --no-restore

      - name: Test with coverage
        run: dotnet test "Lithium.sln" --no-build --verbosity normal --settings tests.runsettings --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Merge coverage reports
        run: reportgenerator -reports:"tests/**/TestResults/**/coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:"Cobertura"

      - name: Publish coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coverage/Cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false }}
        with:
          recreate: true
          path: code-coverage-results.md

  pack-and-upload:
    needs: test
    if: ${{ needs.test.result == 'success' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Install NBGV
        run: dotnet tool install -g nbgv

      - name: Restore dependencies
        run: dotnet restore "Lithium.sln"

      - name: Build Release configuration
        run: dotnet build "Lithium.sln" --no-restore --configuration Release

      - name: Pack NuGet package (pre-release)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: dotnet pack "Lithium.sln" -p:PublicRelease=false --no-build -c Release -o artifacts

      - name: Pack NuGet package (release)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet pack "Lithium.sln" -p:PublicRelease=true --no-build -c Release -o artifacts

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg

  create-github-prerelease:
    needs: pack-and-upload
    if: ${{ needs.pack-and-upload.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package versions
        id: versions
        uses: ./.github/actions/get-all-package-versions

      - name: Create GitHub Release
        uses: ./.github/actions/publish-meta-package
        with:
          core-version: ${{ steps.versions.outputs.core-version }}
          defs-version: ${{ steps.versions.outputs.defs-version }}
          strings-version: ${{ steps.versions.outputs.strings-version }}
          prerelease: true
          github-token: ${{ github.token }}

  create-github-release:
    needs: pack-and-upload
    if: ${{ needs.pack-and-upload.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package versions
        id: versions
        uses: ./.github/actions/get-all-package-versions

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: artifacts

      - name: Create GitHub Release (Core)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versions.outputs.core }}
          name: ${{ steps.versions.outputs.core }}
          files: artifacts/cyv.Lithium.Core.*.nupkg

      - name: Create GitHub Release (Defs)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versions.outputs.defs }}
          name: ${{ steps.versions.outputs.defs }}
          files: artifacts/cyv.Lithium.Defs.*.nupkg

      - name: Create GitHub Release (Strings)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versions.outputs.strings }}
          name: ${{ steps.versions.outputs.strings }}
          files: artifacts/cyv.Lithium.Strings.*.nupkg

      - name: Create GitHub Release (meta)
        uses: ./.github/actions/publish-meta-package
        with:
          core-version: ${{ steps.versions.outputs.core }}
          defs-version: ${{ steps.versions.outputs.defs }}
          strings-version: ${{ steps.versions.outputs.strings }}
          prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
