name: Build and Test Lithium.sln

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore "Lithium.sln"

      - name: Build
        run: dotnet build "Lithium.sln" --no-restore

      - name: Test with coverage
        run: dotnet test "Lithium.sln" --no-build --verbosity normal --settings tests.runsettings --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Merge coverage reports
        run: reportgenerator -reports:"tests/**/TestResults/**/coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:"Cobertura"

      - name: Publish coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coverage/Cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          indicators: true
          output: both
          thresholds: "80 90"

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/Cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false }}
        with:
          recreate: true
          path: code-coverage-results.md

  pack-and-upload:
    needs: test
    if: ${{ needs.test.result == 'success' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Install NBGV
        run: dotnet tool install -g nbgv

      - name: Restore dependencies
        run: dotnet restore "Lithium.sln"

      - name: Build Release configuration
        run: dotnet build "Lithium.sln" --no-restore --configuration Release

      - name: Pack NuGet package (pre-release)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: dotnet pack "Lithium.sln" -p:PublicRelease=false --no-build -c Release -o artifacts

      - name: Pack NuGet package (release)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet pack "Lithium.sln" -p:PublicRelease=true --no-build -c Release -o artifacts

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg

  create-github-prerelease:
    needs: pack-and-upload
    if: ${{ needs.pack-and-upload.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package versions
        id: versions
        uses: ./.github/actions/get-all-package-versions

      - name: Create GitHub Release
        uses: ./.github/actions/publish-meta-package
        with:
          core-version: ${{ steps.versions.outputs.core-version }}
          defs-version: ${{ steps.versions.outputs.defs-version }}
          strings-version: ${{ steps.versions.outputs.strings-version }}
          prerelease: true

  create-github-release:
    needs: pack-and-upload
    if: ${{ needs.pack-and-upload.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"

    outputs:
      core-version: ${{ steps.versions.outputs.core-version }}
      defs-version: ${{ steps.versions.outputs.defs-version }}
      strings-version: ${{ steps.versions.outputs.strings-version }}
      meta-version: ${{ steps.release-meta.outputs.meta-version }}
      any-new-versions: ${{ steps.validate-core.outputs.tag-exists == 'false' || steps.validate-defs.outputs.tag-exists == 'false' || steps.validate-strings.outputs.tag-exists == 'false' || steps.release-meta.outputs.published }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package versions
        id: versions
        uses: ./.github/actions/get-all-package-versions
        with:
          publish-tag: false

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: artifacts

      - name: Validate Core release
        id: validate-core
        uses: "./.github/actions/check-tag"
        with:
          tag-name: cyv.Lithium.Core-v${{ steps.versions.outputs.core-version }}

      - name: Create GitHub Release (Core)
        if: ${{ steps.validate-core.outputs.tag-exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cyv.Lithium.Core-v${{ steps.versions.outputs.core-version }}
          name: cyv.Lithium.Core-v${{ steps.versions.outputs.core-version }}
          files: artifacts/cyv.Lithium.Core.*.nupkg
          prerelease: false

      - name: Validate Core release
        id: validate-defs
        uses: "./.github/actions/check-tag"
        with:
          tag-name: cyv.Lithium.Defs-v${{ steps.versions.outputs.defs-version }}

      - name: Create GitHub Release (Defs)
        if: ${{ steps.validate-defs.outputs.tag-exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cyv.Lithium.Defs-v${{ steps.versions.outputs.defs-version }}
          name: cyv.Lithium.Defs-v${{ steps.versions.outputs.defs-version }}
          files: artifacts/cyv.Lithium.Defs.*.nupkg
          prerelease: false

      - name: Validate Strings release
        id: validate-strings
        uses: "./.github/actions/check-tag"
        with:
          tag-name: cyv.Lithium.Strings-v${{ steps.versions.outputs.strings-version }}

      - name: Create GitHub Release (Strings)
        if: ${{ steps.validate-strings.outputs.tag-exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cyv.Lithium.Strings-v${{ steps.versions.outputs.strings-version }}
          name: cyv.Lithium.Strings-v${{ steps.versions.outputs.strings-version }}
          files: artifacts/cyv.Lithium.Strings.*.nupkg
          prerelease: false

      - name: Create GitHub Release (meta)
        id: release-meta
        uses: ./.github/actions/publish-meta-package
        with:
          core-version: ${{ steps.versions.outputs.core-version }}
          defs-version: ${{ steps.versions.outputs.defs-version }}
          strings-version: ${{ steps.versions.outputs.strings-version }}
          prerelease: false

  publish-nuget-package:
    needs: create-github-release
    if: ${{ needs.create-github-release.result == 'success' && github.ref == 'refs/heads/main' && needs.create-github-release.outputs.any-new-versions == 'true' }}
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Download Core release
        run: |
          gh release download "cyv.Lithium.Core-v${{ needs.create-github-release.outputs.core-version }}" \
          --repo ${{ github.repository }} \
          --pattern "*.nupkg" \
          --dir releases

      - name: Download Defs release
        run: |
          gh release download "cyv.Lithium.Defs-v${{ needs.create-github-release.outputs.defs-version }}" \
          --repo ${{ github.repository }} \
          --pattern "*.nupkg" \
          --dir releases

      - name: Download Strings release
        run: |
          gh release download "cyv.Lithium.Strings-v${{ needs.create-github-release.outputs.strings-version }}" \
          --repo ${{ github.repository }} \
          --pattern "*.nupkg" \
          --dir releases

      - name: Download Meta release
        run: |
          gh release download "${{ needs.create-github-release.outputs.meta-version }}" \
          --repo ${{ github.repository }} \
          --pattern "*.nupkg" \
          --dir releases

      - name: Publish packages to NuGet
        run: |
          dotnet nuget push "./releases/*.nupkg" \
            --api-key ${{ secrets.NUGET_UPDATE_LITHIUM_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate \
            --no-symbols
